export const WS_CONNECTION_BEGIN = 'WS_CONNECTION_BEGIN'
export const WS_CONNECTION_ESTABLISHED = 'WS_CONNECTION_ESTABLISHED'
export const WS_CONNECTION_FAILED = 'WS_CONNECTION_FAILED'
export const WS_CONNECTION_CLOSED = 'WS_CONNECTION_CLOSED'
export const WS_MESSAGE = 'WS_MESSAGE'

export const CONNECTION_STATE_OFF = 'NOT_ON'
export const CONNECTION_STATE_IN_PROGRESS = 'ATTEMPTING_CONNETCION'
export const CONNECTION_STATE_ON = 'CONNECTION_ESTABLISHED'
